server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: SpringBootCRUD

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


info:
  application:
    name: SpringBootCRUD
    version: '@project.version@'